### ISSUE TITLE
'recast' module not found

### ISSUE THREAD

**Issue by jorenbroekema** [conartist6/babel-plugin-recast#9] opened 2021-02-03 10:57 UTC
recast is a peer dependency, so it doesn't get installed. Perhaps make it a normal dependency?

**Comment by conartist6** [comment] 2021-02-03 14:01
I changed it to a peer dependency, because I believe that's what it should be. Do you have some problem with the normal method of resolving peer dependencies, i.e. adding `recast` to your project's dependencies?

**Comment by conartist6** [comment] 2021-02-03 21:07
Basically the problem is that different versions of recast will have subtle differences in how they print. Even if they are only formatting differences they can be breaking in the types of scenarios this plugin is used in. E.g. if you're overwriting the original sources (as a codemod does), different formatting can break comments like `// eslint-ignore-next-line`.

I don't think it's appropriate to pick a specific version of recast (plus I'd have to keep changing it), and if I specify `"recast": "*"` as a dependency then the specific version would be determined by subtleties of the package manager and could cause breaking changes at any time.

That said, a peer dependency is totally worthy of documentation and inclusion in a changelog, which I forgot to do.

**Comment by jorenbroekema** [comment] 2021-02-04 18:05
Fair enough. Agreed yeah, should probably be documented a bit more clearly 😅

**Closed as completed** 2022-02-21 03:53 UTC
